- name: removal of "{{appname}}"
  hosts: all
  become: true
  vars:
   servicestate: stopped
   appstate: absent
   appname: nginx
  tasks:
  - name: installing "{{appname}}"
    apt: 
      name: "{{appname}}"
      state: "{{appstate}}"

  - name: checking for "{{appname}}" service
    service:
      name: "{{appname}}"
      state: "{{servicestate}}"
      enabled: yes